version: '3'

services:
  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: merchant
      MYSQL_USER: admin
      MYSQL_PASSWORD: pass
    ports:
    - 3306:3306
  app:
    build:
      context: .
      dockerfile: ./deployment/docker/Dockerfile
    env_file:
      - ./deployment/docker/.env
    ports:
      - 8080:8080
    volumes:
      - ./config.yaml:/config.yaml
    depends_on:
      - db
    command: ["/usr/local/bin/merchant/wait-for-mysql.sh", "db", "/usr/local/bin/merchant/init.sh"]